name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install  # Adjust if using yarn or pnpm

      - name: Build project
        run: npm run build  # Adjust based on your build command

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch to deploy to
          folder: build  # The output folder (adjust if needed)
          clean: true  # Removes old files before deploying
